# Generated by Django 2.2.6 on 2019-10-31 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Наименование проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('industry', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид деятельности')),
                ('data_send', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('cost', models.CharField(blank=True, max_length=40, null=True, verbose_name='Стоимость проекта')),
                ('square', models.CharField(blank=True, max_length=40, null=True, verbose_name='Площадь земельного участка')),
                ('work', models.CharField(blank=True, max_length=5, null=True, verbose_name='Колличество рабочих')),
                ('company', models.CharField(blank=True, max_length=55, null=True, verbose_name='Организация')),
                ('status', models.SmallIntegerField(choices=[(0, 'Рассмотрение'), (1, 'Сопровождение'), (2, 'Реализация'), (3, 'Завершено')], null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, default=1, max_length=20, null=True, verbose_name='Имя организации')),
                ('contacts', models.CharField(blank=True, default=1, max_length=40, null=True, verbose_name='Контакты организации')),
                ('industry', models.CharField(blank=True, default=1, max_length=30, null=True, verbose_name='Вид деятельности')),
                ('profile_organisation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
