# Generated by Django 2.2.6 on 2019-10-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(blank=True, max_length=40, verbose_name='Контакты организации')),
                ('organisation_name', models.CharField(blank=True, max_length=20, verbose_name='Имя организации')),
                ('industry', models.CharField(blank=True, max_length=30, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='Наименование проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('industry', models.CharField(max_length=30, verbose_name='Вид деятельности')),
                ('data_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.CharField(max_length=40, verbose_name='Стоимость проекта')),
                ('square', models.CharField(max_length=40, verbose_name='Площадь земельного участка')),
                ('work', models.CharField(max_length=5, verbose_name='Колличество рабочих')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRoom.Organisation')),
                ('statement_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
