# Generated by Django 2.2.6 on 2019-10-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль'},
        ),
    ]
