# Generated by Django 2.2.6 on 2019-10-22 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='profile_organisation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='data_send',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
