# Generated by Django 2.2.6 on 2019-10-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='company',
        ),
    ]
