# Generated by Django 2.2.6 on 2019-12-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='worker',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Численность работников'),
        ),
    ]
