# Generated by Django 2.2.6 on 2019-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0002_remove_statement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Рассмотрение'), (1, 'Сопровождение'), (2, 'Реализация'), (3, 'Завершено')], default=0, null=True),
        ),
    ]
