# Generated by Django 2.2.6 on 2019-12-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0002_info_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='energy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Электроснабжение'),
        ),
        migrations.AddField(
            model_name='info',
            name='gas',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AddField(
            model_name='info',
            name='termo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Теплоснабжение'),
        ),
        migrations.AddField(
            model_name='info',
            name='water',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AddField(
            model_name='info',
            name='waterout',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Водоотведение'),
        ),
    ]
