# Generated by Django 2.2.6 on 2019-10-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0002_auto_20191022_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='profile_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile'),
        ),
    ]
