# Generated by Django 2.2.6 on 2019-10-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0003_auto_20191022_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contacts',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Контакты организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='profile_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile'),
        ),
    ]
