# Generated by Django 2.2.6 on 2019-10-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0003_auto_20191018_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Заяка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
