# Generated by Django 2.2.6 on 2019-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0003_auto_20191202_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='invest',
        ),
        migrations.AlterField(
            model_name='info',
            name='energy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Электроснабжение(МВт)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='gas',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Газоснабжение(тыс. куб м/сут)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='termo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Теплоснабжение(Гкал/час)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='territory',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Территория региона(тыс.га)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='water',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Водоснабжение(тыс.куб м/сут)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='waterout',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Водоотведение(тыс. куб м/сут)'),
        ),
    ]
