# Generated by Django 2.2.6 on 2019-10-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0003_auto_20191031_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile')),
                ('zayavka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Statement')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторов',
            },
        ),
    ]
