# Generated by Django 2.2.6 on 2019-10-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0004_auto_20191018_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
