# Generated by Django 2.2.6 on 2019-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0004_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Неактивна'), (1, 'Рассмотрение'), (2, 'Реализация'), (3, 'Завершено')], default=0, null=True),
        ),
    ]
