# Generated by Django 2.2.6 on 2019-11-08 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0004_auto_20191107_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/userRoom/img')),
                ('news_data', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('news_header', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок новости')),
                ('news_text', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
