# Generated by Django 2.2.6 on 2019-11-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связей',
            },
        ),
    ]
