# Generated by Django 2.2.6 on 2019-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0005_auto_20191029_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Started'), (1, 'Done'), (2, 'Error')], null=True),
        ),
    ]
