# Generated by Django 2.2.6 on 2019-10-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0006_auto_20191018_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
