# Generated by Django 2.2.6 on 2019-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0006_statement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Рассмотрение'), (1, 'Сопровождение'), (2, 'Реализация'), (3, 'Завершено')], null=True),
        ),
    ]
