# Generated by Django 2.2.6 on 2019-11-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0006_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='organisation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Организация'),
        ),
    ]
