# Generated by Django 2.2.6 on 2019-10-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0007_auto_20191018_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
