# Generated by Django 2.2.6 on 2019-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0007_connection_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия паспорта'),
        ),
    ]
