# Generated by Django 2.2.6 on 2019-10-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0008_auto_20191018_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_joined',
        ),
    ]
