# Generated by Django 2.2.6 on 2019-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0009_remove_profile_data_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=11, max_length=30, verbose_name='Номер телефона'),
        ),
    ]
