# Generated by Django 2.2.6 on 2019-11-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0010_auto_20191114_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passport_serial',
        ),
    ]
