# Generated by Django 2.2.6 on 2019-10-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0011_auto_20191018_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_profile',
        ),
    ]
