# Generated by Django 2.2.6 on 2019-11-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0011_auto_20191118_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userRoom.Profile'),
        ),
    ]
