# Generated by Django 2.2.6 on 2019-11-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0012_statement_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'неактивна'), (1, 'В сопровождении'), (3, 'Завершено')], default=0, null=True),
        ),
    ]
