# Generated by Django 2.2.6 on 2019-10-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0012_remove_profile_name_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contacts',
            field=models.CharField(blank=True, max_length=40, verbose_name='Контакты организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='industry',
            field=models.CharField(blank=True, max_length=30, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
