# Generated by Django 2.2.6 on 2019-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0013_auto_20191119_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время исполения заявки'),
        ),
    ]
