# Generated by Django 2.2.6 on 2019-11-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0014_statement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время исполения заявки'),
        ),
    ]
