# Generated by Django 2.2.6 on 2019-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0015_auto_20191119_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='Время исполения заявки'),
        ),
    ]
