# Generated by Django 2.2.6 on 2019-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0016_auto_20191119_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='project_name',
            field=models.CharField(default=0, max_length=30, verbose_name='Наименование проекта'),
        ),
    ]
