# Generated by Django 2.2.6 on 2019-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0016_auto_20191021_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
    ]
