# Generated by Django 2.2.6 on 2019-11-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0018_auto_20191120_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.SmallIntegerField(choices=[('0', 'неактивна'), ('1', 'В сопровождении'), ('2', 'Завершено')], default=0, null=True),
        ),
    ]
