# Generated by Django 2.2.6 on 2019-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0026_auto_20191120_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'В рассмотрении'), ('1', 'В сопровождении'), ('2', 'Завершено')], default='0', max_length=5, null=True, verbose_name='статус'),
        ),
    ]
