# Generated by Django 2.2.6 on 2019-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0027_auto_20191121_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
