# Generated by Django 2.2.6 on 2019-11-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0028_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(blank=True, max_length=30, null=True, verbose_name='Территория региона')),
                ('invest', models.CharField(blank=True, max_length=30, null=True, verbose_name='Инвестиции в капитал')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRoom.Region')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
