# Generated by Django 2.2.6 on 2019-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0029_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информацию', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AlterField(
            model_name='statement',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='Наименование проекта'),
        ),
    ]
