# Generated by Django 2.2.6 on 2019-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0031_auto_20191125_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('0', 'Не прочитано'), ('1', 'прочитано')], default='0', max_length=3, null=True, verbose_name='Статус'),
        ),
    ]
