# Generated by Django 2.2.6 on 2019-11-27 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userRoom', '0034_auto_20191126_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data_send',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
